<a href="https://colab.research.google.com/github/hargagan/Machine-Learning/blob/master/Diabetics_dataset_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [23]:
import numpy as np; import pandas as pd; import matplotlib.pyplot as plt; import seaborn as sns
import numpy as np; import pandas as pd; import matplotlib.pyplot as plt; import seaborn as sns
from sklearn.datasets import load_diabetes
from sklearn.preprocessing import MinMaxScaler  # Scaling
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, LogisticRegression, Lasso, Ridge
from sklearn.metrics import mean_squared_error
import warnings; warnings.filterwarnings('ignore')

In [13]:
# Load the breast cancer data
diabetes_ds =  load_diabetes()
X = pd.DataFrame(diabetes_ds.data, columns=diabetes_ds.feature_names)
print(X.head())
y = pd.Series(diabetes_ds.target)
print(f'Input shape: {X.shape}')
print(f'Target shape: {y.shape}')
print(f'Feature names: {diabetes_ds.feature_names}')
print(f'Target names: {diabetes_ds.keys()}')

        age       sex       bmi  ...        s4        s5        s6
0  0.038076  0.050680  0.061696  ... -0.002592  0.019907 -0.017646
1 -0.001882 -0.044642 -0.051474  ... -0.039493 -0.068332 -0.092204
2  0.085299  0.050680  0.044451  ... -0.002592  0.002861 -0.025930
3 -0.089063 -0.044642 -0.011595  ...  0.034309  0.022688 -0.009362
4  0.005383 -0.044642 -0.036385  ... -0.002592 -0.031988 -0.046641

[5 rows x 10 columns]
Input shape: (442, 10)
Target shape: (442,)
Feature names: ['age', 'sex', 'bmi', 'bp', 's1', 's2', 's3', 's4', 's5', 's6']
Target names: dict_keys(['data', 'target', 'frame', 'DESCR', 'feature_names', 'data_filename', 'target_filename', 'data_module'])

In [74]:
# Train-Val-Test split
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.8, test_size = 0.2, random_state = 9001)
features_considered = X_train.columns
print('Dimensions of X_train:', X_train.shape); print('Dimensions of y_train:', y_train.shape)
print('Dimensions of X_test:', X_test.shape); print('Dimensions of y_test:', y_test.shape)

Dimensions of X_train: (353, 10)
Dimensions of y_train: (353,)
Dimensions of X_test: (89, 10)
Dimensions of y_test: (89,)

In [75]:
# Fit a scaler to the training data and transform all the datasets
scaler = MinMaxScaler()
numerical_columns = X_train.select_dtypes(include = ['int64', 'float64']).columns
X_train[numerical_columns] = scaler.fit_transform(X_train[numerical_columns])
X_test[numerical_columns] = scaler.transform(X_test[numerical_columns])

In [27]:
Lasso?

# Unregularized Linear Regression Model

In [76]:
lr_model_1 = LinearRegression()
lr_model_1 = lr_model_1.fit(X_train, y_train)
# Look at the predictive performance of this model
y_pred_lr_list = lr_model_1.predict(X_train[features_considered])
mse = mean_squared_error(y_true = y_train, y_pred = y_pred_lr_list)
lr_mse = np.round(mse, 2)
print('LinearRegression - Training MSE = ', lr_mse)

LinearRegression - Training MSE =  2882.42

# Lasso Regularization

In [77]:
lr_model_2 = Lasso(alpha=1, random_state=9001)
lr_model_2 = lr_model_2.fit(X_train[features_considered], y_train)

y_pred_lr_a_list = lr_model_2.predict(X_train[features_considered])
mse = mean_squared_error(y_true = y_train, y_pred = y_pred_lr_a_list)
lr_a_mse = np.round(mse, 2)
print('Lasso Regression - Training MSE = ', lr_a_mse)

Lasso Regression - Training MSE =  3019.54

In [78]:
lr_model_3 = Ridge(alpha=1, random_state=9001)
lr_model_3 = lr_model_3.fit(X_train[features_considered], y_train)

y_pred_lr_r_list = lr_model_3.predict(X_train[features_considered])
mse = mean_squared_error(y_true = y_train, y_pred = y_pred_lr_r_list)
lr_r_mse = np.round(mse, 2)
print('Ridge Regression - Training MSE = ', lr_r_mse)

Ridge Regression - Training MSE =  2904.38

In [79]:
pd.DataFrame({"Feature": features_considered, "Coefficients - LR": lr_model_1.coef_, "Coefficients - Lasso": lr_model_2.coef_, "Coefficient - Ridge": lr_model_3.coef_}).round(3)

  Feature  Coefficients - LR  Coefficients - Lasso  Coefficient - Ridge
0     age             -9.017                -0.000               -6.726
1     sex            -19.227                -7.035              -18.778
2     bmi            124.151               121.012              117.779
3      bp             81.828                57.382               78.641
4      s1           -207.800                -0.000              -24.044
5      s2            115.733                -0.000              -18.400
6      s3             40.324               -42.474              -42.663
7      s4             60.420                 0.000               40.573
8      s5            178.651               111.778              108.939
9      s6             25.882                 3.476               28.734

In [80]:
pd.DataFrame({"Feature": ["MSE"], "Linear-Regression": lr_mse, "Lasso-LR": lr_a_mse, "Ridge-LR": lr_r_mse}).round(2)

  Feature  Linear-Regression  Lasso-LR  Ridge-LR
0     MSE            2882.42   3019.54   2904.38